pipeline {
  agent any
  stages {
    stage("Clone repository") {
      steps {
        sh "rm -r ./CI-Pipeline-Appclone"
        sh "rmdir CI-Pipeline-Appclone"  
        sh "git clone https://github.com/MP-Prime/CI-Pipeline-Appclone"
      }
    }  
    stage("Test app") {
      steps {
        sh "sudo apt update"
        sh  "sudo apt install -y python3-pip"
        sh "cd ~"
        sh "pip install -r requirements.txt"
        sh "python3 app.py"
      }
    }  
    stage("Upload to Docker") {
      steps {
        sh ""
      }
    }
    stage("Get from Docker") {
      steps {
        sh ""
      }
    }  
    stage("Deploy in Kubernetes") {
      steps {
        sh ""
      }
    }
  }
}