pipeline {
  agent any
  stages {
    stage("Test app") {
      steps {
        sh "sudo apt update"
        sh  "sudo apt install -y python3-pip"
        sh "pip install -r -y requirements.txt"
        sh "python3 app.py"
      }
    }  
    stage("Upload to Docker") {
      steps {
        sh ""
      }
    }
    stage("Get from Docker") {
      steps {
        sh ""
      }
    }  
    stage("Deploy in Kubernetes") {
      steps {
        sh ""
      }
    }
  }
}